### ISSUE TITLE
Updates to TODO status

### ISSUE THREAD

**Issue by gnanet** [akoeb/amacube#28]
## TODO

This is a uncomplete list of things that need to be done with this plugin
* Add functionality similar to Mailzu (http://sourceforge.net/projects/mailzu/)
  - [ ] Add left side menu area
  - [ ] Add "show summary"
  - [x] Add Administrator functionality - already done in #25 
  - [ ] Add Site quarantine summary
  - [x] Add Site quarantine list - if this means a full list with all quarantine messages, it is done in #25
  - [ ] Add "click on email title" to see email content - started a new pure-roundcube way of solution in #24
* Improve item selection mechanism

**Comment by Ratchet-master** [comment]
Is this still underway or has this also been left unmaintained?

**Comment by gnanet** [comment]
My use case is only done to serve a few users, and only the "show email content" function was essential,which was a raw combination of a configured mailzu on the webmail server vhost and roundcube/amacube, and that solution was sufficient for the users.

If there is a need to develop these further, i would still need a bit help,as i am only a hobby-programmer,so i am short in a lot of PHP and specially RCMail development knowledge.

**Comment by Ratchet-master** [comment]
Cool. Thanks for the info. 
I'm also only a hobby programmer but am reviewing the code - due to seeing the below issue with the side menu to view quarantine, (which I see is unticked):

![2021-01-21 23_12_36](https://user-images.githubusercontent.com/59712443/105423897-41681500-5c3e-11eb-974c-651540020ffc.png)

(Inaccessible), but the filter settings seems to be working from the settings menu.
(FYI - roundcube 1.4.10)

I'll let you know if I find anything.
